#!/usr/bin/env node

var pjson = require('./package.json');
var program = require('commander');
var fs = require('fs');
var spawn = require('child_process').spawn;
var chalk = require('chalk');
var file = require('./lib/files');
var password = require('./lib/random-password');
var tmpl1 = fs.readFileSync(__dirname + '/templates/htaccess').toString();
var tmpl2 = fs.readFileSync(__dirname + '/templates/htpasswd').toString();
var pass = password.generate();
var user = '';

program
    .version( pjson.version )
    .description('Use this program to restrict access to the web folder using htpasswd.')
    .option('-u, --user [user]', 'username. Required.')
    .option('-p, --passwd [passwd]', 'password. Optional. Leave blank if you want to have autogenerated password')
    .parse(process.argv);


if( !program.user ) {
    console.log(chalk.red('Error:') + ' ' + chalk.bold('Username is missing.') + ' Use ldaccess --help for futher information.\n');
    return;
}

user = program.user;

if( program.passwd ) {
    pass = program.passwd;
}

// Check for files
//
if( file.fileExists(file.getCurrentDirectoryPath() + '/.htaccess') || file.fileExists(file.getCurrentDirectoryPath() + '/.htpasswd') ) {
    console.log(chalk.yellow('Warning:') + ' There already are .htaccess and/or .htpasswd files.\n');
    return;
}

// Generate HTACCESS
//
var htaccess = tmpl1.replace('{{dir}}', file.getCurrentDirectoryPath());

fs.writeFile(file.getCurrentDirectoryPath() + '/.htaccess', htaccess, function() {
    fs.chmodSync(file.getCurrentDirectoryPath() + '/.htaccess', 0444);
});

// Generate HTPASSWD
//
var cmd = spawn('openssl', ['passwd', '-crypt', pass]);
cmd.stdout.on('data', function(data) {
    var hash = data.toString().trim();
    var htpasswd = tmpl2.replace('{{user}}', user).replace('{{password}}', hash);
    fs.writeFile(file.getCurrentDirectoryPath() + '/.htpasswd', htpasswd, function() {
        fs.chmodSync(file.getCurrentDirectoryPath() + '/.htpasswd', 0444);
    });
});

// Done. End program
//
console.log('\n' + chalk.green.bold('Done.') + ' Access grunted to user "' + user + '" with password "' + pass + '".\n');
